DEVENGAGE-1610 Axios proxy bug
purecloudlabs/platform-client-sdk-common pull request #521
Opened 2023-02-27 10:21 UTC by dginty4

2023-02-27 10:27 UTC, dginty4 commented on resources/sdk/purecloudjavascript/templates/ApiClient.mustache
> +const { HttpsProxyAgent } = require('hpagent')
I couldn't get the import to work like the other imports, anybody know how I could?

2023-02-27 10:31 UTC, dginty4 commented on resources/sdk/purecloudjavascript/templates/ApiClient.mustache
> +            }
I also can't seem to get the formatting right, it looks right on any editor I open it on except here

2023-02-27 17:01 UTC, timsmithgenesys reviewed
Did we get a permanent proxy set up to be able to add tests? If so, tests should be added. If not, tests should be added when the proxy is deployed and accessible during the build.

2023-02-27 17:05 UTC, carnellj-genesys requested changes
1.  Didn't have any technical comments besides what Tim pointed out.
2. I don't see any tests here.  I would like to see a test case using the target proxy.  While manual tests are good, automated tests will help us find stuff later if somebody changes something again.

Nice work on this Declan.

2023-02-28 15:09 UTC, dginty4 commented on resources/sdk/purecloudjavascript/templates/ApiClient.mustache
> +const { HttpsProxyAgent } = require('hpagent')
Thanks Tim. `import { HttpsProxyAgent } from 'hpagent'` doesn't seem to work so I'll have to leave it as is

2023-02-28 15:28 UTC, dginty4 commented
Would someone be able to build the sdk local? I think the security group for the proxy servers EC2 instance might only allow my IP through but I'm not 100%

2023-02-28 18:18 UTC, carnellj-genesys approved these changes

2023-03-01 16:42 UTC, merged