Fixing Intermittent Build Errors
purecloudlabs/platform-client-sdk-common pull request #528
Opened 2023-03-10 15:57 UTC by HemanthDogiparthi12

2023-03-10 17:06 UTC, timsmithgenesys requested changes

2023-03-10 17:06 UTC, timsmithgenesys commented on resources/sdk/purecloudjavascript/scripts/test/index.js
> +		console.log('after wait');
remove debugging trace

2023-03-10 17:36 UTC, HemanthDogiparthi12 commented on resources/sdk/purecloudjavascript/scripts/test/index.js
> +		setTimeout(() => {
Yes the test waits for the async to complete before marking it as passed. Verified this in local.

The errors we are seeing are more related to the profileSkills not being persisted by the time getUser API call happens.
The settimeout function waits for the configured delay and then executes the getUser call which gives us the necessary buy-in time ( I assume this here) for the profileSkills to be persisted and the asserts to pass.

But as you suggested we can do a retry of the call and see how the builds look. Will update the patch and send it.

2023-03-10 18:40 UTC, carnellj-genesys approved these changes

2023-03-10 18:40 UTC, carnellj-genesys commented on resources/sdk/purecloudjavascript/scripts/test/index.js
> +		setTimeout(() => {
Good first pass.  I would try to implement the retry (No harm in doing it) and then we can see if gets things to quiet down.

2023-03-13 14:06 UTC, HemanthDogiparthi12 commented on resources/sdk/purecloudjavascript/scripts/test/index.js
> +		setTimeout(() => {
Added retry for Python, Js and .NET SDKs

2023-03-13 17:42 UTC, timsmithgenesys commented on resources/sdk/purecloudpython/scripts/compile.sh
> +echo "Install watchdog..."
update comment (retry not watchdog)

2023-03-13 17:42 UTC, timsmithgenesys approved these changes

2023-03-14 09:13 UTC, merged